<?php

/**
 * Baseline Native YouMeOS Sparks Roster
 *
 * @package    Xophz_Compass_Event_Horizon
 * @subpackage Xophz_Compass_Event_Horizon/includes/api
 */
class Xophz_Compass_Event_Horizon_Default_Sparks {

	/**
	 * Return baseline registry of native YouMeOS sparks.
	 *
	 * @return array
	 */
	public static function get_all() {
		return array(
			'u-spark-plugs' => array( 'id' => 'u-spark-plugs', 'title' => 'Add/Remove Spark Plugs', 'description' => 'Manage and discover installed sparks', 'icon' => 'fal fa-plug', 'color' => '#ff9800', 'brand_color' => '#ff9800', 'brandColor' => '#ff9800', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/u-spark-plugs/?fullspark=true', 'version' => '2.4.0' ),
			'my-compass-suite' => array( 'id' => 'my-compass-suite', 'title' => 'My Compass', 'description' => 'My Compass Ecosystem Dashboard', 'icon' => 'fal fa-compass', 'color' => '#62c9ff', 'brand_color' => '#62c9ff', 'brandColor' => '#62c9ff', 'category' => 'portal', 'type' => 'portal', 'pwa_url' => '/spark/my-compass-suite/?fullspark=true', 'version' => '2.4.0' ),
			'u-nucleos' => array( 'id' => 'u-nucleos', 'title' => 'Nucleos', 'description' => 'Your central desktop environment', 'icon' => 'fal fa-atom-alt', 'color' => '#ff007a', 'brand_color' => '#ff007a', 'brandColor' => '#ff007a', 'category' => 'portal', 'type' => 'spark', 'pwa_url' => '/spark/u-nucleos/?fullspark=true', 'version' => '2.4.0' ),
			'omega-source' => array( 'id' => 'omega-source', 'title' => 'THEOS', 'description' => 'Account settings and identity hub', 'icon' => 'fal fa-omega', 'color' => '#62c9ff', 'brand_color' => '#62c9ff', 'brandColor' => '#62c9ff', 'category' => 'portal', 'type' => 'spark', 'pwa_url' => '/spark/omega-source/?fullspark=true', 'version' => '2.4.0' ),
			'helios' => array( 'id' => 'helios', 'title' => 'Helios', 'description' => 'Solar-powered content dashboard', 'icon' => 'fal fa-solar-system', 'color' => '#D9BE6F', 'brand_color' => '#D9BE6F', 'brandColor' => '#D9BE6F', 'category' => 'portal', 'type' => 'portal', 'pwa_url' => '/spark/helios/?fullspark=true', 'version' => '2.4.0' ),
			'nexus' => array( 'id' => 'nexus', 'title' => 'Nexos', 'description' => 'Connected intelligence network', 'icon' => 'fal fa-atom', 'color' => '#62c9ff', 'brand_color' => '#62c9ff', 'brandColor' => '#62c9ff', 'category' => 'portal', 'type' => 'portal', 'pwa_url' => '/spark/nexus/?fullspark=true', 'version' => '2.4.0' ),
			'logos' => array( 'id' => 'logos', 'title' => 'Logos', 'description' => 'Admin web management portal', 'icon' => 'fal fa-spider-web', 'color' => '#3dee98', 'brand_color' => '#3dee98', 'brandColor' => '#3dee98', 'category' => 'portal', 'type' => 'portal', 'pwa_url' => '/spark/logos/?fullspark=true', 'version' => '2.4.0' ),
			'noosphere' => array( 'id' => 'noosphere', 'title' => 'Noosphere', 'description' => 'Explore the collective thought space', 'icon' => 'fal fa-galaxy', 'color' => '#b300ff', 'brand_color' => '#b300ff', 'brandColor' => '#b300ff', 'category' => 'portal', 'type' => 'portal', 'pwa_url' => '/spark/noosphere/?fullspark=true', 'version' => '2.4.0' ),
			'gaea' => array( 'id' => 'gaea', 'title' => 'Gaea OS', 'description' => 'Living earth environment system', 'icon' => 'fal fa-globe-americas', 'color' => '#4CAF50', 'brand_color' => '#4CAF50', 'brandColor' => '#4CAF50', 'category' => 'portal', 'type' => 'spark', 'pwa_url' => '/spark/gaea/?fullspark=true', 'version' => '2.4.0' ),
			'calculator' => array( 'id' => 'calculator', 'title' => 'Calculator', 'description' => 'Quick math at your fingertips', 'icon' => 'fal fa-calculator', 'color' => '#2196F3', 'brand_color' => '#2196F3', 'brandColor' => '#2196F3', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/calculator/?fullspark=true', 'version' => '2.4.0' ),
			'holosweeper' => array( 'id' => 'holosweeper', 'title' => 'Holosweeper', 'description' => 'Classic minesweeper with a neon twist', 'icon' => 'fal fa-bomb', 'color' => '#FF5252', 'brand_color' => '#FF5252', 'brandColor' => '#FF5252', 'category' => 'games', 'type' => 'spark', 'pwa_url' => '/spark/holosweeper/?fullspark=true', 'version' => '2.4.0' ),
			'solitaire' => array( 'id' => 'solitaire', 'title' => 'Solitaire', 'description' => 'The timeless card game', 'icon' => 'fal fa-spade', 'color' => '#ff0000', 'brand_color' => '#ff0000', 'brandColor' => '#ff0000', 'category' => 'games', 'type' => 'spark', 'pwa_url' => '/spark/solitaire/?fullspark=true', 'version' => '2.4.0' ),
			'blackjack' => array( 'id' => 'blackjack', 'title' => 'Blackjack', 'description' => 'Hit or stand in this casino classic', 'icon' => 'fal fa-club', 'color' => '#3b82f6', 'brand_color' => '#3b82f6', 'brandColor' => '#3b82f6', 'category' => 'games', 'type' => 'spark', 'pwa_url' => '/spark/blackjack/?fullspark=true', 'version' => '2.4.0' ),
			'bubblegum' => array( 'id' => 'bubblegum', 'title' => 'Bubblegum', 'description' => 'Manage Tasks & Focus', 'icon' => 'fal fa-check-circle', 'color' => '#FF1493', 'brand_color' => '#FF1493', 'brandColor' => '#FF1493', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/bubblegum/?fullspark=true', 'version' => '2.4.0' ),
			'notepad' => array( 'id' => 'notepad', 'title' => 'Alphabet Soup', 'description' => 'A rich text scratchpad for notes', 'icon' => 'fal fa-soup', 'color' => '#FB8C00', 'brand_color' => '#FB8C00', 'brandColor' => '#FB8C00', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/notepad/?fullspark=true', 'version' => '2.4.0' ),
			'terminal' => array( 'id' => 'terminal', 'title' => 'HoloShell', 'description' => 'Holographic command-line interface', 'icon' => 'fal fa-terminal', 'color' => '#10b981', 'brand_color' => '#10b981', 'brandColor' => '#10b981', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/terminal/?fullspark=true', 'version' => '2.4.0' ),
			'sys-monitor' => array( 'id' => 'sys-monitor', 'title' => 'System Monitor', 'description' => 'Real-time system performance metrics', 'icon' => 'fal fa-tachometer-average', 'color' => '#69f0ae', 'brand_color' => '#69f0ae', 'brandColor' => '#69f0ae', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/sys-monitor/?fullspark=true', 'version' => '2.4.0' ),
			'chronos' => array( 'id' => 'chronos', 'title' => 'Chronos', 'description' => 'Master time with clocks and timers', 'icon' => 'fal fa-infinity', 'color' => '#ff4081', 'brand_color' => '#ff4081', 'brandColor' => '#ff4081', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/chronos/?fullspark=true', 'version' => '2.4.0' ),
			'jukebox' => array( 'id' => 'jukebox', 'title' => 'Beat Salad', 'description' => 'Community jukebox and radio station', 'icon' => 'fal fa-salad', 'color' => '#b388ff', 'brand_color' => '#b388ff', 'brandColor' => '#b388ff', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/jukebox/?fullspark=true', 'version' => '2.4.0' ),
			'paint' => array( 'id' => 'paint', 'title' => 'Night\'s Light', 'description' => 'Draw and paint under the moonlight', 'icon' => 'fal fa-moon-stars', 'color' => '#00f2fe', 'brand_color' => '#00f2fe', 'brandColor' => '#00f2fe', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/paint/?fullspark=true', 'version' => '2.4.0' ),
			'xophz-magic-formula' => array( 'id' => 'xophz-magic-formula', 'title' => 'Magic Formula', 'description' => 'Brew powerful automation recipes', 'icon' => 'fal fa-cauldron', 'color' => '#a78bfa', 'brand_color' => '#a78bfa', 'brandColor' => '#a78bfa', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/xophz-magic-formula/?fullspark=true', 'version' => '2.4.0' ),
			'cafeteria' => array( 'id' => 'cafeteria', 'title' => 'Cafeteria Food', 'description' => 'Quick bites and daily specials', 'icon' => 'fal fa-burger-soda', 'color' => '#ffc107', 'brand_color' => '#ffc107', 'brandColor' => '#ffc107', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/cafeteria/?fullspark=true', 'version' => '2.4.0' ),
			'debug-console' => array( 'id' => 'debug-console', 'title' => 'Debug Console', 'description' => 'Inspect logs and runtime diagnostics', 'icon' => 'fal fa-bug', 'color' => '#ff5555', 'brand_color' => '#ff5555', 'brandColor' => '#ff5555', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/debug-console/?fullspark=true', 'version' => '2.4.0' ),
			'tourguide' => array( 'id' => 'tourguide', 'title' => 'Galaxy Guide', 'description' => 'Interactive walkthrough of the platform', 'icon' => 'fal fa-thumbs-up u-tilt-left-45', 'color' => '#06b6d4', 'brand_color' => '#06b6d4', 'brandColor' => '#06b6d4', 'category' => 'core', 'type' => 'spark', 'pwa_url' => '/spark/tourguide/?fullspark=true', 'version' => '2.4.0' ),
			'welcome-u' => array( 'id' => 'welcome-u', 'title' => 'Welcome', 'description' => 'Your first steps into YouMeOS', 'icon' => 'fal fa-hand-spock', 'color' => '#8b5cf6', 'brand_color' => '#8b5cf6', 'brandColor' => '#8b5cf6', 'category' => 'core', 'type' => 'spark', 'pwa_url' => '/spark/welcome-u/?fullspark=true', 'version' => '2.4.0' ),
			'app-launcher' => array( 'id' => 'app-launcher', 'title' => 'Launch Pad', 'description' => 'Discover and launch all installed Sparks', 'icon' => 'fal fa-rocket-launch', 'color' => '#ff5252', 'brand_color' => '#ff5252', 'brandColor' => '#ff5252', 'category' => 'core', 'type' => 'spark', 'pwa_url' => '/spark/app-launcher/?fullspark=true', 'version' => '2.4.0' ),
			'enchiridion' => array( 'id' => 'enchiridion', 'title' => 'Enchiridion', 'description' => 'The sacred manual of knowledge', 'icon' => 'fal fa-book-spells', 'color' => '#a855f7', 'brand_color' => '#a855f7', 'brandColor' => '#a855f7', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/enchiridion/?fullspark=true', 'version' => '2.4.0' ),
			'blackbox' => array( 'id' => 'blackbox', 'title' => 'BlackBOX', 'description' => 'System internals and diagnostics', 'icon' => 'fal fa-cube', 'color' => '#38bdf8', 'brand_color' => '#38bdf8', 'brandColor' => '#38bdf8', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/blackbox/?fullspark=true', 'version' => '2.4.0' ),
			'neon-notes' => array( 'id' => 'neon-notes', 'title' => 'Scratch Paper', 'description' => 'Quick sticky notes that glow', 'icon' => 'fal fa-sticky-note', 'color' => '#FB8C00', 'brand_color' => '#FB8C00', 'brandColor' => '#FB8C00', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/neon-notes/?fullspark=true', 'version' => '2.4.0' ),
			'snake' => array( 'id' => 'snake', 'title' => 'Neon Snake', 'description' => 'Classic snake with electric style', 'icon' => 'fal fa-snake', 'color' => '#00ff66', 'brand_color' => '#00ff66', 'brandColor' => '#00ff66', 'category' => 'games', 'type' => 'spark', 'pwa_url' => '/spark/snake/?fullspark=true', 'version' => '2.4.0' ),
			'cookie-jar' => array( 'id' => 'cookie-jar', 'title' => 'Cookie Jar', 'description' => 'Manage cookies and sweet treats', 'icon' => 'fal fa-cookie', 'color' => '#ff9800', 'brand_color' => '#ff9800', 'brandColor' => '#ff9800', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/cookie-jar/?fullspark=true', 'version' => '2.4.0' ),
			'xophz-lemonade-stand' => array( 'id' => 'xophz-lemonade-stand', 'title' => 'Lemon Aid', 'description' => 'Fresh lemonade economy simulator', 'icon' => 'fal fa-lemon', 'color' => '#eab308', 'brand_color' => '#eab308', 'brandColor' => '#eab308', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/xophz-lemonade-stand/?fullspark=true', 'version' => '2.4.0' ),
			'local-produce' => array( 'id' => 'local-produce', 'title' => 'Local Produce', 'description' => 'Browse fresh community offerings', 'icon' => 'fal fa-apple-crate', 'color' => '#4caf50', 'brand_color' => '#4caf50', 'brandColor' => '#4caf50', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/local-produce/?fullspark=true', 'version' => '2.4.0' ),
			'trenchess' => array( 'id' => 'trenchess', 'title' => 'Trenchess', 'description' => 'Strategic chess in the trenches', 'icon' => 'fal fa-chess-knight', 'color' => '#ffc107', 'brand_color' => '#ffc107', 'brandColor' => '#ffc107', 'category' => 'games', 'type' => 'spark', 'pwa_url' => '/spark/trenchess/?fullspark=true', 'version' => '2.4.0' ),
			'trophy-case' => array( 'id' => 'trophy-case', 'title' => 'Trophy Case', 'description' => 'Showcase your earned achievements', 'icon' => 'fal fa-trophy', 'color' => '#ffd700', 'brand_color' => '#ffd700', 'brandColor' => '#ffd700', 'category' => 'games', 'type' => 'spark', 'pwa_url' => '/spark/trophy-case/?fullspark=true', 'version' => '2.4.0' ),
			'suggestion-box' => array( 'id' => 'suggestion-box', 'title' => 'Suggestion Bo', 'description' => 'Submit ideas and feature requests', 'icon' => 'fal fa-box-ballot', 'color' => '#ffcc00', 'brand_color' => '#ffcc00', 'brandColor' => '#ffcc00', 'category' => 'core', 'type' => 'spark', 'pwa_url' => '/spark/suggestion-box/?fullspark=true', 'version' => '2.4.0' ),
			'polos' => array( 'id' => 'polos', 'title' => 'POLOS', 'description' => 'Fractal Consensus & Navigational Governance', 'icon' => 'fal fa-drafting-compass', 'color' => '#62c9ff', 'brand_color' => '#62c9ff', 'brandColor' => '#62c9ff', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/polos/?fullspark=true', 'version' => '2.4.0' ),
			'bugnet' => array( 'id' => 'bugnet', 'title' => 'Bug-Catching Net', 'description' => 'Report and track platform bugs', 'icon' => 'fal fa-debug', 'color' => '#1e9682', 'brand_color' => '#1e9682', 'brandColor' => '#1e9682', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/bugnet/?fullspark=true', 'version' => '2.4.0' ),
			'lunch-room' => array( 'id' => 'lunch-room', 'title' => 'Lunch Room', 'description' => 'Team hangout and coffee chat', 'icon' => 'fal fa-coffee-pot', 'color' => '#2196F3', 'brand_color' => '#2196F3', 'brandColor' => '#2196F3', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/lunch-room/?fullspark=true', 'version' => '2.4.0' ),
			'telescope' => array( 'id' => 'telescope', 'title' => 'Chaos', 'description' => 'Peer into the cosmic unknown', 'icon' => 'fal fa-meteor', 'color' => '#818cf8', 'brand_color' => '#818cf8', 'brandColor' => '#818cf8', 'category' => 'portal', 'type' => 'spark', 'pwa_url' => '/spark/telescope/?fullspark=true', 'version' => '2.4.0' ),
			'tesseract' => array( 'id' => 'tesseract', 'title' => 'The Tesseract', 'description' => '4D hosting platform', 'icon' => 'fal fa-police-bo', 'color' => '#0284c7', 'brand_color' => '#0284c7', 'brandColor' => '#0284c7', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/tesseract/?fullspark=true', 'version' => '2.4.0' ),
			'vip-club' => array( 'id' => 'vip-club', 'title' => 'VIP Club', 'description' => 'Exclusive perks for premium members', 'icon' => 'fal fa-mask', 'color' => '#00f2fe', 'brand_color' => '#00f2fe', 'brandColor' => '#00f2fe', 'category' => 'core', 'type' => 'spark', 'pwa_url' => '/spark/vip-club/?fullspark=true', 'version' => '2.4.0' ),
			'social-preview' => array( 'id' => 'social-preview', 'title' => 'Social Preview', 'description' => 'Preview your social sharing cards', 'icon' => 'fal fa-share-alt', 'color' => '#42b883', 'brand_color' => '#42b883', 'brandColor' => '#42b883', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/social-preview/?fullspark=true', 'version' => '2.4.0' ),
			'wizards-tower' => array( 'id' => 'wizards-tower', 'title' => 'Wizard\'s  Tower', 'description' => 'Advanced development configuration', 'icon' => 'fal fa-chess-rook', 'color' => '#a78bfa', 'brand_color' => '#a78bfa', 'brandColor' => '#a78bfa', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/wizards-tower/?fullspark=true', 'version' => '2.4.0' ),
			'wp-admin' => array( 'id' => 'wp-admin', 'title' => 'WP Admin', 'description' => 'WordPress administration panel', 'icon' => 'fab fa-wordpress', 'color' => '#21759b', 'brand_color' => '#21759b', 'brandColor' => '#21759b', 'category' => 'developer', 'type' => 'spark', 'pwa_url' => '/spark/wp-admin/?fullspark=true', 'version' => '2.4.0' ),
			'midnight-nerd' => array( 'id' => 'midnight-nerd', 'title' => 'Midnight Nerd', 'description' => 'Direct line of contact to DP', 'icon' => 'fal fa-dice-d20', 'color' => '#8d105e', 'brand_color' => '#8d105e', 'brandColor' => '#8d105e', 'category' => 'core', 'type' => 'spark', 'pwa_url' => '/spark/midnight-nerd/?fullspark=true', 'version' => '2.4.0' ),
			'author-note' => array( 'id' => 'author-note', 'title' => 'Author\'s Note', 'description' => 'Vision and philosophy of the Youniverse', 'icon' => 'fal fa-file-signature', 'color' => '#62c9ff', 'brand_color' => '#62c9ff', 'brandColor' => '#62c9ff', 'category' => 'core', 'type' => 'spark', 'pwa_url' => '/spark/author-note/?fullspark=true', 'version' => '2.4.0' ),
			'media-drive' => array( 'id' => 'media-drive', 'title' => 'My Nimbus', 'description' => 'Decentralized File Storage', 'icon' => 'fal fa-cloud', 'color' => '#0ea5e9', 'brand_color' => '#0ea5e9', 'brandColor' => '#0ea5e9', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/media-drive/?fullspark=true', 'version' => '2.4.0' ),
			'oscar' => array( 'id' => 'oscar', 'title' => 'Trash', 'description' => 'The Social Dumpster (Oscar)', 'icon' => 'fal fa-dumpster', 'color' => '#10b981', 'brand_color' => '#10b981', 'brandColor' => '#10b981', 'category' => 'picnic', 'type' => 'spark', 'pwa_url' => '/spark/oscar/?fullspark=true', 'version' => '2.4.0' ),
			'swag-shop' => array( 'id' => 'swag-shop', 'title' => 'Swag Shop', 'description' => 'Official Hall of the Gods merchandise', 'icon' => 'fal fa-shopping-bag', 'color' => '#ff9800', 'brand_color' => '#ff9800', 'brandColor' => '#ff9800', 'category' => 'core', 'type' => 'spark', 'pwa_url' => '/spark/swag-shop/?fullspark=true', 'version' => '2.4.0' ),
			'my-planner' => array( 'id' => 'my-planner', 'title' => 'My R.O. Planner', 'description' => 'Plan and organize with My Compass Planner', 'icon' => 'fal fa-calendar-alt', 'color' => '#0ea5e9', 'brand_color' => '#0ea5e9', 'brandColor' => '#0ea5e9', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/my-planner/?fullspark=true', 'version' => '2.4.0' ),
			'yellow-links' => array( 'id' => 'yellow-links', 'title' => 'Yellow Links', 'description' => 'Public web registry and community directory', 'icon' => 'fal fa-book-open', 'color' => '#FFCC00', 'brand_color' => '#FFCC00', 'brandColor' => '#FFCC00', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/yellow-links/?fullspark=true', 'version' => '2.4.0' ),
			'u-skiptrace' => array( 'id' => 'u-skiptrace', 'title' => 'Skip Tracing', 'description' => 'Public records & skip trace intelligence', 'icon' => 'fal fa-search-location', 'color' => '#62c9ff', 'brand_color' => '#62c9ff', 'brandColor' => '#62c9ff', 'category' => 'productivity', 'type' => 'spark', 'pwa_url' => '/spark/u-skiptrace/?fullspark=true', 'version' => '2.4.0' ),
			'fresh-mints' => array( 'id' => 'fresh-mints', 'title' => 'Fresh Mints', 'description' => 'Practice launcher and skip-trace intelligence', 'icon' => 'fal fa-sparkles', 'color' => '#10b981', 'brand_color' => '#10b981', 'brandColor' => '#10b981', 'category' => 'productivity', 'type' => 'webspark', 'pwa_url' => '/spark/fresh-mints/?fullspark=true', 'version' => '2.4.0' ),
			'my-lawfirm' => array( 'id' => 'my-lawfirm', 'title' => 'My Lawfirm', 'description' => 'Legal practice management and case tracking platform', 'icon' => 'fal fa-balance-scale', 'color' => '#2563eb', 'brand_color' => '#2563eb', 'brandColor' => '#2563eb', 'category' => 'productivity', 'type' => 'webspark', 'pwa_url' => '/spark/my-lawfirm/?fullspark=true', 'version' => '2.4.0' ),
			'card-vault' => array( 'id' => 'card-vault', 'title' => 'Card Vault', 'description' => 'Trade Desk & POS for Card Show Dealers', 'icon' => 'fal fa-cards', 'color' => '#f59e0b', 'brand_color' => '#f59e0b', 'brandColor' => '#f59e0b', 'category' => 'productivity', 'type' => 'webspark', 'pwa_url' => '/spark/card-vault/?fullspark=true', 'version' => '2.4.0' ),
		);
	}
}
